#version 450

layout (local_size_x = 16, local_size_y = 16) in;
layout(rgba32f, binding = 1) uniform image2D image;

struct TestStorage {
    float x;
    float y;
};
layout (binding = 2) buffer TestStorageBuffer {
    TestStorage test_floats[];
};

void main() {	
    int index = int(gl_GlobalInvocationID.x % 2);
    imageStore(image, ivec2(gl_GlobalInvocationID.xy), vec4(test_floats[index].x, test_floats[index].y, 0, 1));
}
